### PR TITLE
Message model

### PR DESCRIPTION
**Pull request by anand2312**
This PR adds a few new models;
- Embed
- Message
and re-organizes the Avatar asset into a general Asset model that is used everywhere instead.

Avatar's tests have been modified to work for Asset; new tests have been written for Embed (I'll write tests for Message tomorrow)

## Stuff to note
- Message content will not be a string , but a dict for system messages: this hasn't been handled in the Message model (it is handled in the lower level `resist.types` TypedDict for Message). Content is casted to a string; what should we do about it?
- Revolt does not seem to care about embed colours right now
- `Message.author`, `Message.channel`, `Message.mentions` should all be modified to use full `Member` and `Channel` models when they are made

### CODE REVIEW

**Comment by an-dyy** [comment]
This looks good. Although I would say consistency and style could be better, E.g this PR introduces `attr.define`, whilst the rest of the library uses `attr.s`

Imports should be either **always**
```py
from attr import s
```
or always
```py
import attr
```
Currently the wrapper uses the latter. Another nitpick would be `if` statements, I find it tends to look better with a space between each other if-statement, E.g
```py
if foo in bar:
    ...

if baz in qux:
    ...
```
Also perhaps a **base** model would help with future model building?
Also for the system message issue, I'd make it a new attribute, such as `Message.system` and just have `Message.content` as None

**Comment by anand2312** [comment]
@an-dyy I've used attrs.define as attrs calls it the "modern API with sane defaults", but I can switch it to attr.s if you prefer that

**Comment by anand2312** [comment]
Also re: setting Message.content to None: that would mean it's type becomes `None | str`, and the end-user would have to keep doing type-checks (`if message.content is None`) which would be very annoying

**Comment by anand2312** [comment]
btw you should approve running CI on this because it counts me as a first-time contrib

**Comment by an-dyy** [comment]
> @an-dyy I've used attrs.define as attrs calls it the "modern API with sane defaults" and uses it across documentation, but I can switch it to attr.s if you prefer that. (Also `from attr import s` is so ugly 😩, it should only be `import attr` and `@attr.s`)

Yea ok, let's switch to define then

**Comment by an-dyy** [comment]
> Also re: setting Message.content to None: that would mean it's type becomes `None | str`, and the end-user would have to keep doing type-checks (`if message.content is None`) which would be very annoying
> 
> 

What other idea is there than that?

**Pull request merged**
